---
title: "Project Proposal"
author:
    - YOUR_NAME
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    keep_md: yes
urlcolor: blue
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Objective

A maximum of three sentences outlining the "big picture" objective(s) of the project.
It should not be technical, and answer the "Why You Should Care" question - i.e. justify the managerial relevance.
My grandmother should be able to understand it.

## Research Question

SOMETHING (technical jargon can used added here)

**Sub-Questions:** (if any)

* ...

### Type of Question

The research question I will answer is a **INSERT_ANSWER** question.

Replace **INSERT_ANSWER** with one of:^[These question types are borrowed from a paper by Jeff Leek and Roger Peng in their paper: "What is the question?"[-@Leek1314].
]

1. Descriptive
2. Exploratory
3. Inferential
4. Predictive
5. Causal
6. Mechanistic

## Data

Keep the choice which applies to your project:

- I have downloaded the necessary data for this project. The script to download the data is [`data/download-data.R`](data/download-data.R)^[
The instructors need to be able to run this script.
Make sure you have updated the `renv` in the project template.
]
- I have not yet downloaded the final data for this project because the event I want to study has yet to occur, but have a working R script that downloads data for an earlier time period. The script to download the data is [`data/download-data.R`](data/download-data.R)^[
The instructors need to be able to run this script.
Make sure you have updated the `renv` in the project template.
]
  - **NOTES:** Only use this option if you are using the Twitter API, and the event you plan to study has not occurred by the proposal deadline
- I am yet to download the necessary data for this project
  - **NOTES:** Selecting this option comes with a **30% penalty** to your grade as you have not met the requirements for the proposal.

## Data Description

Provide a short paragraph explaning the data you will use in your project.
Where is it from?
How many rows and columns?
What are the important columns for your analysis?
Provide a citation if you are using data you didn't collect yourself.

## Analysis Workflow

My workflow will follow the following steps:

* **Step 1**. SOMETHING
  * Some details
  * More details (if needed)
* **Step 2**. SOMETHING
  * Some details
  * More details (if needed)
* ...

## Communicating Results

Explain how you plan to report your results. 
For example, what tables and figures do you expect your report will contain.
Will the table be a regression table or something else?
Will the figure(s) be a box-plot, scatterplot, something else?

## Word Count

Number of Words: `r wordcountaddin::word_count("proposal.Rmd")`

## References